### ISSUE TITLE
readme: Please improve on suboptimal notes on licensing

### ISSUE THREAD

**Issue by hartwork** [pavelsof/django-mirror#1]
The readme currently reads:

> GPL. You can do what you want with this code as long as you let others do the same.

I see two issues with this:
- You require version 3 and nothing else [according to `setup.py`](https://github.com/pavelsof/django-mirror/blob/55ac57cf526ffa9ab6eb8899ceeacd77efdaf5ef/setup.py#L34). Please make that clear here, i.e. to contrast against `version 3 or later`, `version 2 or later`, `version 2 (and nothing else)`.
- That summary sentence is a rather hurtful summary of the GPL in my eyes, e.g. there are things that it forbids both the user and his/her derivatives users to do altogether. If someone doesn't know the GPL in 2020, they are better served by doing a proper research I think than with a not-ideal summary. You could provide a link to https://www.gnu.org/licenses/gpl-3.0.en.html instead maybe.

What do you think?

**Comment by pavelsof** [comment]
Thank you for your feedback! You are right, that short line at the end of the README does not do much good. I will specify the version and provide a link to the licence text. But apart from that, do you think that GPLv3 is inappropriate for this package?

**Comment by hartwork** [comment]
Hi @pavelsof, I'm glad you're taking the feedback well.  I mostly pick from GPL, AGPL, MIT and CC0 for my own projects depending on what I want people to be legally able and have to do with the code these days.  Personally, I think the GPL 3 is a fine license and not inappropriate for this package, but I don't know about your intentions in detail.  Does it fit your intentions?

**Comment by pavelsof** [comment]
Well, it was fair feedback, my sentence there was an unneeded and quite one-sided summary of the licence (: 

To be honest, I have not given enough thought about these things. Yes, I have read the GPLv3 licence and I subscribe to the copyleft philosophy, but I do not claim that I fully understand the legalese. I am using CodeMirror in two Django projects I am working on, there was some common code and put it out in a package. If somebody else finds it useful, that would be nice; if it helps further the copyleft cause, then even better.

**Comment by cdrx** [comment]
Most Django packages are MIT or BSD licensed. Would you consider relicensing it as LGPL v3? That keeps the copyleft benefits but allows it to be used in more projects.

**Comment by pavelsof** [comment]
@cdrx, my reading of GPLv3 is that if a company is running Django on their servers and they want to use django-mirror, they are under no obligation to disclose their source code because running your code on your servers does not count as distribution. Similar for agencies creating software on behalf of other companies. I guess re-licensing it to LGPLv3 would only affect open-source packages that would have django-mirror as a pip dependency. Please correct me if I am wrong.

**Comment by cdrx** [comment]
@pavelsof you are correct, however `admin.[js|css]` & `init.js` are distributed (to the end user's browser) under the current GPLv3 licence -- `django-mirror` can not currently be used in non-GPL projects.

Relicensing to LGPLv3 would not impact anyone currently using the library, but would allow it to be used by a wider audience of developers.

**Comment by pavelsof** [comment]
Thank you, @cdrx, I did not think about the frontend files. You are right, I will change the licence and will make a release today (:

**Comment by cdrx** [comment]
Thanks @pavelsof :)
